export const CollectionStates = {
    NOT_RECORDING: 'NOT_RECORDING',
    RECORDING: 'RECORDING',
    BEFORE_UPLOAD: 'BEFORE_UPLOAD',
    TRANSITIONING: 'TRANSITIONING',
    QC_ERROR: 'QC_ERROR',
    UPLOAD_ERROR: 'UPLOAD_ERROR',
};
